### ISSUE TITLE
Add support for optional parameters

### ISSUE THREAD

**Issue by kurtisvg** [googleapis/genai-toolbox#475]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

Currently, all parameters in Toolbox are required. The value for a parameter must be provided -- either by the LLM, bound at the SDK level, or bound as an authenticated parameter. 

However, this can mean introduce several tools that all do roughly the same thing, with only slightly variations. Sometimes this is a reasonable solution -- our testing shows that models handle multiple tools better than optional parameters. However as models continue to get better, this advantage will likely fade. 

There are a couple of implementation details to figure out, specifically:

1. If we mark a parameter as optional, what is the default value? 
2. Should we allow for optional parameters to default to null? 

### Suggested Solution(s)

Option 1: Add a `default` field to parameters, that enables users to specify a default value.

e.g.
```yaml
  parameters:
    - name: name
      type: string
      default: "some-default-value"
      description: The name of the hotel.
```

If this parameter is invoked without specifying `name`, the parameter would default to "some-default-value"

### Alternatives Considered

Option 2a: Add a `optional` field to parameters, that defaults to `false`:
e.g.
```yaml
  parameters:
    - name: name
      type: string
      optional: true
      description: The name of the hotel.
```

This could default to either `null` or some zero value for different types e.g.` 0` for ints.

Option 2b: Add a `required` field to parameters, that defaults to `true`:
e.g.
```yaml
  parameters:
    - name: name
      type: string
      required: true
      description: The name of the hotel.
```

This could default to either `null` or some zero value for different types e.g.` 0` for ints.

Option 3:  Add both `required` field and `default` field to parameters, that defaults to `true`:
```yaml
  parameters:
    - name: name
      type: string
      required: true
      default: "some-value"
      description: The name of the hotel.
```

This could provide "null" if default is unset, and the value of "default" otherwise.
