### ISSUE TITLE
Add authentication/authorization support for Microsoft Entra ID

### ISSUE THREAD

**Issue by brandon-powers** [googleapis/genai-toolbox#482]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

👋 

Currently, the toolbox only supports Google for OAuth 2.0, listed [here](https://googleapis.github.io/genai-toolbox/resources/authservices/). I'd like to extend support to Microsoft Entra ID, alongside Google, to enable use in Authorized Invocation and Authenticated Parameters.

### Suggested Solution(s)

- Implementation of an `AuthService` [here](https://github.com/googleapis/genai-toolbox/tree/main/internal/auth), with a new `microsoft` directory
- Config update [here](https://github.com/googleapis/genai-toolbox/blob/main/internal/server/config.go#L285)

e.g.
```yaml
authServices:
  my_auth_app_3:
    kind: microsoft
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
    clientId: "6731de76-14a6-49ae-97bc-6eba6914391e"
```

### Alternatives Considered

Native integration is preferable vs. something like a proxy. It could drive more adoption for organizations that desire toolbox features but are already using Entra ID.
