### ISSUE TITLE
Add data source support for Iceberg (catalogs)

### ISSUE THREAD

**Issue by brandon-powers** [googleapis/genai-toolbox#483]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

Here are the currently supported data sources: https://googleapis.github.io/genai-toolbox/resources/sources/. 

The idea is to add support for a source that can interact with Iceberg catalogs; whether it's REST-based, AWS Glue, or eventually BigQuery Metastore. The tools would be related to namespaces, tables, metadata exploration (e.g. `get_average_file_size_for_table`), etc. 

I'd imagine this being used for mostly read-only use cases, as it wouldn't rely on a dedicated compute engine, but an **[iceberg-go](https://github.com/apache/iceberg-go)** implementation from Apache.

Similar to the addition of Entra ID support, I think the toolbox provides useful out-of-the-box functionality & performance that can be leveraged, instead of creating a separate MCP server.  

### Suggested Solution(s)

- `iceberg` addition to the Tools and Sources directories for implementation using `iceberg-go`
- Config update [here](https://github.com/googleapis/genai-toolbox/blob/main/internal/server/config.go#L163)
- Reference examples from [Neo4j](https://github.com/googleapis/genai-toolbox/pull/189) & [Couchbase](https://github.com/googleapis/genai-toolbox/pull/307)

### Alternatives Considered

For the REST-based catalog, we may be able to utilize the HTTP source, though a direct integration would be useful + can branch by catalog type. 

### Additional Details

I'd be interested in implementing this, though wanted to raise it for feedback before doing so.

**Comment by kurtisvg** [comment]
Hey @brandon-powers -- definitely open to accepting contributions on this. 

I'm not familiar with iceberg at all, so will rely on your input on what makes the most sense. Could you provide sketchs for what a tools config might look like for those 3 options you outlined?

**Comment by debabsah** [comment]
Hi @kurtisvg, this one has been quiet for a while, so if @brandon-powers is not actively working on it I would be glad to take it on. I work on data tooling (I have the mssql tools in flight in this repo) and Iceberg catalogs are squarely in my wheelhouse.

To answer your question about what a tools config might look like, here is a sketch that follows the current source/tool shape. I would sequence the REST catalog first (most broadly useful and cleanest to land), then add Glue and BigQuery Metastore as follow-ups, all read-only via [apache/iceberg-go](https://github.com/apache/iceberg-go):

```yaml
kind: source
name: iceberg-source
type: iceberg
catalog: rest                    # rest first; glue / bigquery-metastore as follow-ups
uri: ${ICEBERG_REST_URI}         # e.g. https://catalog.example.com
warehouse: ${ICEBERG_WAREHOUSE}  # optional
---
kind: tool
name: list_namespaces
type: iceberg-list-namespaces
source: iceberg-source
description: List namespaces in the Iceberg catalog.
---
kind: tool
name: list_tables
type: iceberg-list-tables
source: iceberg-source
description: List tables in a namespace.
---
kind: tool
name: describe_table
type: iceberg-describe-table
source: iceberg-source
description: Get a table's schema, partition spec, snapshots, and metadata.
---
kind: toolset
name: iceberg_catalog_tools
tools:
  - list_namespaces
  - list_tables
  - describe_table
```

Each tool stays a thin, read-only wrapper over an iceberg-go catalog call (namespace, table, and metadata exploration, including the `get_average_file_size_for_table` idea from the issue), following the Neo4j (#189) and Couchbase (#307) source-addition pattern.

If that scoping looks right, would you welcome PRs?  - starting with the REST catalog source plus those three exploration tools? 
If you do welcome PRs, anything you would want to be shaped differently?
