### ISSUE TITLE
Add option to define & select "data source tools"

### ISSUE THREAD

**Issue by brandon-powers** [googleapis/genai-toolbox#487]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

Each data source requires custom tool definitions, though likely has common operations that can be defined once & reused by many.

The toolbox could offer:
  - common built-in tool implementations by source
  - option to select built-in tools by source

### Suggested Solution(s)

For example,
1. Using Postgres, queries against the information schema / PG catalog could be abstracted into common tools (e.g. `list_tables`, `list_schemas`). 
2. Using Trino / Iceberg, queries against common metadata tables could be used ([docs](https://trino.io/docs/current/connector/iceberg.html#metadata-tables)):
- `get_table_average_file_size`
- `get_number_of_snapshots`
- `get_manifest_entries`

Then, when defining the source,
```yaml
sources:
    my-pg-source:
        kind: postgres
        host: 127.0.0.1
        port: 5432
        database: my_db
        user: ${USER_NAME}
        password: ${PASSWORD}
        source_tools: list_tables,list_schemas # comma-separated string of tool names, with "all" as catch-all
OR
        source_tools: 
            list_tables: false
            list_schemas: true
```

It would increase the out-of-the-box value for particular sources.
- Configure source(s) & enable source tools
- Deploy toolbox to your infra
- Start testing with a client
- Define custom query tools & update config

With that being said, this would be an added abstraction, so it's possible having common toolsets elsewhere using the same `tools` mechanism makes more sense. 

### Alternatives Considered

Instead of integrating with sources, the toolbox could offer extension toolsets, where there's a path for the user to include common source tools when deploying.
