### ISSUE TITLE
getting error when using local mysql

### ISSUE THREAD

**Issue by shashank-google** [googleapis/genai-toolbox#501]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

toolbox version 0.4.0+binary.darwin.amd64.0.4.0.4ed16ccd18768ac02402356f9660526b3452418b

### Environment

1. OS type and version: (output of `uname -a`)
Darwin agarwalsh-macbookpro2.roam.internal 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6000 arm64

2. How are you running Toolbox:   
As a downloaded binary (e.g. from `curl -O https://storage.googleapis.com/genai-toolbox/v0.4.0/darwin/amd64//toolbox`)

### Client

NA

### Expected Behavior

./toolbox --tools-file "tools.yaml"

### Current Behavior

./toolbox --tools-file "tools.yaml"
2025-04-28T12:07:21.750592-07:00 ERROR "unable to parse tool file at \"tools.yaml\": \"mysql\" is not a valid kind of tool" 

### Steps to reproduce?

tools.yaml
```
sources:
  my-mysql-source:
    kind: mysql
    host: 127.0.0.1
    port: 3307
    database: AdventureWorks2014
    user: root
    password: root
tools:
  get-table-structure:
    kind: mysql
    source: my-mysql-source
    description: Get table schema
    parameters:
      - name: tablename
        type: string
        description: The name of the table.
    statement: Describe $1;
toolsets:
  my-toolset:
    - get-table-structure
```

**Comment by Yuan325** [comment]
Hi Shashank, seems like there's an error in the config. The tools kind is `mysql-sql` instead of `mysql`. ref: https://googleapis.github.io/genai-toolbox/resources/tools/mysql-sql/

Fix as below:
```
sources:
  my-mysql-source:
    kind: mysql
    host: 127.0.0.1
    port: 3307
    database: AdventureWorks2014
    user: root
    password: root
tools:
  get-table-structure:
    kind: mysql-sql
    source: my-mysql-source
    description: Get table schema
    parameters:
      - name: tablename
        type: string
        description: The name of the table.
    statement: Describe $1;
toolsets:
  my-toolset:
    - get-table-structure
```


Feel free to reopen this if it still doesn't work.
