### ISSUE TITLE
Unable to create a new name using  postgres-sql tool

### ISSUE THREAD

**Issue by prateek2408** [googleapis/genai-toolbox#527]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

0.4.0

### Environment

1. OS type and version: Linux Debian 
2. How are you running Toolbox:  As a downloaded binary 

### Client

1. Client:  Agent Development Kit
2. Version: NA
3. Example: If possible, please include your code of configuration:

```
tools:
  create-new-classroom:
    kind: postgres-sql
    source: my-cloud-sql-pg-source
    description: Create a new classroom with a given name in Hogwarts school
    statement: |
      CREATE TABLE $1 (ClassroomID SERIAL PRIMARY KEY, ClassroomName VARCHAR(255) NOT NULL, RoomNumber VARCHAR(255), Capacity INT, GradeLevel VARCHAR(50), SubjectArea VARCHAR(50));
    parameters:
      - name: name
        type: string
        description: The name of the classroom
```
agent.py
```
from google.adk.agents import Agent
from google.adk.tools.toolbox_tool import ToolboxTool

toolbox = ToolboxTool("http://0.0.0.0:5000")

tools = toolbox.get_toolset(toolset_name='my_first_toolset')

root_agent = Agent(
    model='gemini-2.0-flash-001',
    name='classroom_agent',
    description='Agent to answer questions abouts classroom in a school',
    instruction=(
        "You are a helpful agent who can answer questions about a classroom of a school. Use the tools to answer the question"
        ),
    tools=tools,
)
```

### Expected Behavior

A new table should have been created

### Current Behavior

Gives an error- 
```
DEBUG "error while invoking tool: unable to execute query: ERROR: syntax error at or near \"$1\" (SQLSTATE 42601)"
```

### Steps to reproduce?

1. Use postgres-sql tool tool and write a sample CREATE Table command
2. Connect with Agent development kit
3. Write a prompt to invoke create table
...

### Additional Details

SQL monitoring also shows that the variable is not replaced with exact value

```
 db=my_test_db,user=postgres ERROR:  syntax error at or near "$1" at character 14
```
