### ISSUE TITLE
Support  usage of `parameters` fields with non-filtering parameters

### ISSUE THREAD

**Issue by aaronlcic** [googleapis/genai-toolbox#535]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

0.4.0+binary.linux.amd64.0.4.0.4ed16ccd18768ac02402356f9660526b3452418b

### Environment

1. Linux aaronpc2025 6.8.0-59-generic #61-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 11 23:16:11 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
2. Downloaded from https://github.com/googleapis/genai-toolbox/releases

### Expected Behavior

When running a mysql query tool through MCP Inspector, it should return the rows inside the table.

### Current Behavior

But when trying to run this mysql tool through MCP Inspector, the following error occurs: "unable to execute query: Error 1146 (42S02): Table 'test.$2' doesn't exist"
This means that the statement inside the tool in tools.yaml isn't placing the parameters inside the statement. This is the yaml code:
```
yaml
sources:
  source1:
    kind: mysql
    host: 127.0.0.1
    port: 3306
    database: test
    user: ${MYSQL_USER}
    password: ${MYSQL_PASS}
tools:
  select_mcp_mysql:
    kind: mysql-sql
    source: source1
    description: Read from database.
    parameters:
      - name: column_names
        type: string
        description: The name of the columns, separated by commas. If you want to select all columns, use '*'.
      - name: table
        type: string
        description: The name of the table.
      - name: instruction
        type: string
        description: The instruction given by the user, including where, order by, group by statements.
    statement: SELECT $1 FROM $2 $3;

```
In the docs found here https://googleapis.github.io/genai-toolbox/resources/tools/ this is the format used to insert parameters inside the query, so it should work. The example found here https://googleapis.github.io/genai-toolbox/resources/tools/mysql-sql/ uses ? instead, which returns syntax errors too, even when using simple queries like SELECT ? FROM ?

### Steps to reproduce?

1. Create tools.yaml with the code above
2. Have a functional MySQL server and user & password envs
3. ./toolbox --tools-file tools.yaml
4. In another terminal: npx @modelcontextprotocol/inspector (following https://googleapis.github.io/genai-toolbox/getting-started/mcp_quickstart/)
5. Try running this tool

**Comment by Yuan325** [comment]
Hi @aaronlcic, thanks for opening this issue! The `mysql-sql` tool uses different syntax (https://googleapis.github.io/genai-toolbox/resources/tools/mysql-sql/).

Let me know if this statement works! : `SELECT ? FROM ? ?;`

**Comment by aaronlcic** [comment]
> Hi [@aaronlcic](https://github.com/aaronlcic), thanks for opening this issue! The `mysql-sql` tool uses different syntax (https://googleapis.github.io/genai-toolbox/resources/tools/mysql-sql/).
> 
> Let me know if this statement works! : `SELECT ? FROM ? ?;`

Nope: "unable to execute query: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? ?' at line 1". Even when removing "instruction" and leaving only SELECT ? FROM ?; it doesn't work.

**Comment by aaronlcic** [comment]
Leaving only SELECT ? from users; being ? = user_id it returns the same answer for all rows:
{
    ?: "user_id" (literally user_id, it doesn't replace it)
}

**Comment by Yuan325** [comment]
Is your statement `SELECT 'user_id' from users;`? If that's the case, it is expected to return the string "user_id" for the number of rows that you have.

Example data with 2 rows: 
{user_id: foo, other_field: bar},
{user_id: foo2, other_field: bar2}

Try this statement for the tool in your configuration file: `SELECT * FROM users WHERE user_id = ?;`

To test the tool with the above example data, you can set the `user_id` parameter as either `foo` or `foo2`.

**Comment by aaronlcic** [comment]
> Is your statement `SELECT 'user_id' from users;`? If that's the case, it is expected to return the string "user_id" for the number of rows that you have.
> 
> Try this statement: `SELECT * FROM users WHERE user_id = ?;`

That one does work. Does that mean that I can't put paremeters inside SELECT nor FROM? Because using SELECT ? and using user_id in MCP Inspector seems to be adding '' around it

**Comment by Yuan325** [comment]
I just tested it locally and unfortunately it wouldn't work. And you're right, since the parameter is a string, it will add quotes around it.

Were you looking to run a custom statement? We recently release a `postgres-execute-sql` tool (https://googleapis.github.io/genai-toolbox/resources/tools/postgres-execute-sql/) that takes one input parameter `sql` and execute that sql statement against the source. This is currently only available to postgres but we are looking to expand it soon. Will this solve your use case?

**Comment by aaronlcic** [comment]
Yes, I guess I'll stick with postgresql

**Comment by Yuan325** [comment]
I'll keep this bug open for when we add execute-sql tool to mysql. :)

**Comment by manuelrech** [comment]
I am getting the same with Postgres. Anyone can help? Tools without the `$1` work fine. It seems like parameters can be passed to the WHERE statement but not to the FROM, as mentioned previously. 

```yaml
sources:
  postgres_source:
    kind: postgres
    host: localhost
    port: 5432
    database: Data_Sandbox
    user: postgres
    password: passpass
tools:
  get_all_from_table:
    kind: postgres-sql
    source: postgres_source
    description: Get all rows from a specific table
    parameters:
      - name: table_name
        type: string
        description: The name of the table to get all rows from
    statement: SELECT * FROM $1;
  list_tables:
    kind: postgres-sql
    source: postgres_source
    description: Shows all table names in the public schema of the database.
    statement: SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
toolsets:
  inspect_db:
    - get_all_from_table
```


`unable to execute query: ERROR: syntax error at or near "$1" (SQLSTATE 42601)`
