### ISSUE TITLE
Tools with `authRequired` specified are still callable through MCP APis

### ISSUE THREAD

**Issue by kurtisvg** [googleapis/genai-toolbox#543]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

any

### Environment

N/A

### Client

1. Client: any MCP client
2. Version: any
3. Example: If possible, please include your code of configuration:

### Expected Behavior

When I call tools with `authRequired` specified, they should return a 401 error. E.g. 

```yaml
search-hotels-by-id:
kind: postgres-sql
source: my-pg-source
description: Search for hotels based on ID.
parameters:
    - name: id
      type: integer
      description: The ID of the hotel.
statement: SELECT * FROM hotels WHERE id = $1;
authRequired:
    - google-auth
```

### Current Behavior

Currently tools with `authRequired` specified can still be called when using the MCP inspector (or another MCP client). This is because auth is not supported in MCP.

However, we should just disallow the tool call in these instances (probably with a 401 error). 

### Steps to reproduce?

1. ?
2. ?
3. ?
...
