### ISSUE TITLE
HTTP tool without parameters causes error

### ISSUE THREAD

**Issue by vikiscience** [googleapis/genai-toolbox#564]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

toolbox version 0.6.0, us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.5.0

### Environment

1. OS type and version: e.g. Windows 11, Kubernetes 1.31.
2. How are you running Toolbox: 
  - As a downloaded binary (e.g. from `curl -O https://storage.googleapis.com/genai-toolbox/v$VERSION/linux/amd64/toolbox`)
  - As a container (e.g. from `us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:$VERSION`)

### Client

1. Client: [Autogen](https://microsoft.github.io/autogen/stable/user-guide/core-user-guide/components/workbench.html#mcp-workbench)
2. Version: 0.5.6 
3. Example: If possible, please include your code of configuration:

```python
import asyncio
from autogen_ext.tools.mcp import McpWorkbench, SseServerParams, mcp_server_tools

MCP_SERVER_URL = 'http://localhost:5000/mcp/sse'

mcp_server_params = SseServerParams(url=MCP_SERVER_URL)
wb = McpWorkbench(mcp_server_params)
mcp_tools = asyncio.run(mcp_server_tools(mcp_server_params))

print(mcp_tools)
```

### Expected Behavior

If I configure the HTTP tool without any parameters, I expect the Toolbox to handle it in the same manner as e.g. a Sqlite tool without parameters. Namely that the client will get the `inputSchema={'type': 'object', 'properties': {}, 'required': []}` in both cases.

### Current Behavior

The HTTP tool without parameters returns to client an `inputSchema={'type': 'object', 'properties': {}, 'required': None}`., which causes a client to throw an exception:

`TypeError: 'NoneType' object is not iterable`

However, Sqlite tool without parameters is working just fine.

### Steps to reproduce?

1. Install Autogen with MCP:
```
autogen-agentchat==0.5.6
autogen-ext[mcp]==0.5.6 
```
2. Start some dummy HTTP API or use an existing URL that can respond.
3. Start Toolbox with the following tools:
```
sources:
  my-http-source:
    kind: http
    baseUrl: http://localhost:4000  # or smth else
    timeout: 10s  # default to 30s
tools:
  get-health:
    kind: http
    source: my-http-source
    method: GET
    path: /health
    description: Tool to get health from the example API
    # queryParams: []
    # bodyParams: []
    # headerParams: []
toolsets:
  my-toolset-monitoring:
    - get-health
```
4. Run the script provided above and see the error.
