### ISSUE TITLE
[bigquery-sql] Unable to use statement as parameter in parameterized query. 

### ISSUE THREAD

**Issue by Yohan-GRNR** [googleapis/genai-toolbox#566]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

toolbox version 0.5.0

### Environment

How are you running Toolbox:   
  - On Cloud Run with this in my Dockerfile
```
RUN wget https://storage.googleapis.com/genai-toolbox/v0.5.0/linux/amd64/toolbox && \
    chmod +x toolbox
```  

My tools.yaml
```
# tools.yaml
sources:
  my_bigquery_us_source:
    kind: bigquery
    project: "gcp-project-111111" 
    location: "US"                  # US multi-region

  my_bigquery_eu_source:
    kind: bigquery
    project: "gcp-project-111111"  
    location: "EU"                  # EU multi-region

tools:
  run_custom_query_us:
    kind: "bigquery-sql"
    description: "Runs a custom BigQuery query against US-based data."
    source: my_bigquery_us_source 
    statement: "@query"
    parameters: 
      - name: query 
        type: string
        description: "The SQL query to execute in the US region."

  run_custom_query_eu:
    kind: "bigquery-sql"
    description: "Runs a custom BigQuery query against EU-based data."
    source: my_bigquery_eu_source 
    statement: "@query"
    parameters: 
      - name: query 
        type: string
        description: "The SQL query to execute in the EU region."

toolsets:
  all-tools:
    - run_custom_query_us
    - run_custom_query_eu
```

Using : `https://myCloudRun-1111.us-central1.run.app/mcp/all-tools/sse`

### Client

Client: Claude web & MCP Inspector v0.12.0

### Expected Behavior

Should inject the strings (query) Claude or MCP Inspector sent.

### Current Behavior

**Syntax error: Unexpected \"@\" at [1:1], invalidQuery**

MCP Inspector logs:  
```
tools/call
▼
Request:
{
  "method": "tools/call",
  "params": {
    "name": "run_custom_query_eu",
    "arguments": {
      "query": "SELECT * gcp-project-111111.Store_location.All_brands_shop_location_candidate LIMIT 10"
    },
    "_meta": {
      "progressToken": 5
    }
  }
}
Response:
{
  "content": [
    {
      "type": "text",
      "text": "unable to execute query: googleapi: Error 400: Syntax error: Unexpected \"@\" at [1:1], invalidQuery"
    }
  ],
  "isError": true
}
```

### Steps to reproduce?

Make Cloud Run files update: 
1. `docker build -t gcr.io/gcp-project-111111/bigquery-claude-tool:latest .`
2. `docker push gcr.io/gcp-project-111111/bigquery-claude-tool:latest`
3. `gcloud run deploy bigquery-claude-tool   --image gcr.io/gcp-project-111111/bigquery-claude-tool:latest   --region us-central1   --project gcp-project-111111`   

Test it :
1. Connect to MCP Inspector
2. Add the `https://myCloudRun-1111.us-central1.run.app/mcp/all-tools/sse` (fake link)
3. Select SSE
4. Select tools and enter a raw query (e.g: `SELECT * gcp-project-111111.Store_location.All_brands_shop_location_candidate LIMIT 10` )

### Additional Details

✅Temporary solution find :  

Use `"EXECUTE IMMEDIATE @query"`  instead of `"@query"` in the yaml file.  

But with this trick, we can't make complex queries.

e.g:
```

tools:
  run_custom_query_us:
    kind: "bigquery-sql"
    description: "Runs a custom BigQuery query against US-based data."
    source: my_bigquery_us_source
    statement: "EXECUTE IMMEDIATE @query"
    parameters:
      - name: query
        type: string
        description: "The SQL query to execute in the US region."` 

```

🛑 I tried and don't works: 
    - _all with and without out **" "**_  -
- $query
- $1
- {query}
- ${query}

**Comment by kurtisvg** [comment]
Looking at your tool, I think this is partially a documentation fix, and partially a feature request.

Currently the `bigquery-sql` tools executes SQL and the parameters are passed in as query parameters, which [helps prevent SQL injection.](https://cloud.google.com/bigquery/docs/parameterized-queries). The problem with the tool you've descriptor is that it's essentially a SQL parameter. I think this is a documentation fix to more clearly call out the query is executed with parameterized queries. 

There are legitimate uses cases for a tool that takes a string in as query and executes it. We added `postgres-execute-sql` which does this for Postgres. We should add something similar for BQ.

**Comment by Yuan325** [comment]
Hi @Yohan-GRNR we have a [PR](#589) that updates the existing documentations. Would like to get some feedback from you before we merge this. Let us know if the wordings are clear. Thank you!

**Comment by Yuan325** [comment]
Hi @Yohan-GRNR , we have added the `bigquery-execute-sql` tool that takes a sql query as input. Please refer to the docs [here](https://googleapis.github.io/genai-toolbox/resources/tools/bigquery-execute-sql/).

To use the `bigquery-execute-sql` tool, add the following to your tools configuration file:
```
tools:
  run_custom_query_us:
    kind: bigquery-execute-sql
    source: my_bigquery_us_source 
    description: Use this tool to execute sql statement.
```

The tool takes one input parameter `sql`, and run it against the source.

I'll go ahead and close this bug. :)
