### ISSUE TITLE
Select the queries server for Bigquery tool

### ISSUE THREAD

**Issue by Yohan-GRNR** [googleapis/genai-toolbox#567]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

toolbox version 0.5.0

### Environment

How are you running Toolbox:   
  - On Cloud Run with this in my Dockerfile
```
RUN wget https://storage.googleapis.com/genai-toolbox/v0.5.0/linux/amd64/toolbox && \
    chmod +x toolbox
```  

My tools.yaml
```
# tools.yaml
sources:
  my_bigquery_us_source:
    kind: bigquery
    project: "gcp-project-111111" 
    location: "US"                  # US multi-region

  my_bigquery_eu_source:
    kind: bigquery
    project: "gcp-project-111111"  
    location: "EU"                  # EU multi-region

tools:
  run_custom_query_us:
    kind: "bigquery-sql"
    description: "Runs a custom BigQuery query against US-based data."
    source: my_bigquery_us_source 
    statement: "EXECUTE IMMEDIATE @query"
    parameters: 
      - name: query 
        type: string
        description: "The SQL query to execute in the US region."

  run_custom_query_eu:
    kind: "bigquery-sql"
    description: "Runs a custom BigQuery query against EU-based data."
    source: my_bigquery_eu_source 
    statement: "EXECUTE IMMEDIATE @query"
    parameters: 
      - name: query 
        type: string
        description: "The SQL query to execute in the EU region."

toolsets:
  all-tools:
    - run_custom_query_us
    - run_custom_query_eu
```

Using : `https://myCloudRun-1111.us-central1.run.app/mcp/all-tools/sse`

### Client

Client: Claude web & MCP Inspector v0.12.0

### Expected Behavior

Should use the good tool and use the `location` parameter to query with success the BQ database.

### Current Behavior

Issue: `"unable to execute query: googleapi: Error 400: Not found: Dataset gcp-project-111111:Store_location was not found in location US at [1:1], invalidQuery"`  

```
**Request**:
{
  "method": "tools/call",
  "params": {
    "name": "run_custom_query_eu",
    "arguments": {
      "query": "SELECT * FROM gcp-project-111111.Store_location.All_brands_shop_location_candidate LIMIT 10"
    },
    "_meta": {
      "progressToken": 7
    }
  }
}
Response:
{
  "content": [
    {
      "type": "text",
      "text": "unable to execute query: googleapi: Error 400: Not found: Dataset gcp-project-111111:Store_location was not found in location US at [1:1], invalidQuery"
    }
  ],
  "isError": true
}

**initialize**
   ▼
   Request:
   {
     "method": "initialize"
   }
   Response:
   {
     "capabilities": {
       "tools": {
         "listChanged": false
       }
     },
     "serverInfo": {
       "name": "Toolbox",
       "version": "0.5.0+binary.linux.amd64.0.5.0.9a5d76e2dc66eaf0d2d0acf9f202a17539879ffe"
     }
   }


### Steps to reproduce?

Make Cloud Run files update: 
1. `docker build -t gcr.io/gcp-project-111111/bigquery-claude-tool:latest .`
2. `docker push gcr.io/gcp-project-111111/bigquery-claude-tool:latest`
3. `gcloud run deploy bigquery-claude-tool   --image gcr.io/gcp-project-111111/bigquery-claude-tool:latest   --region us-central1   --project gcp-project-111111`   

Test it :
1. Connect to MCP Inspector
2. Add the `https://myCloudRun-1111.us-central1.run.app/mcp/all-tools/sse` (fake link)
3. Select SSE
4. Select the `run_custom_query_eu` tool and enter a raw query (e.g: `SELECT * gcp-project-111111.Store_location.All_brands_shop_location_candidate LIMIT 10` ) who is in **EU server**.

### Additional Details

I tried :

- `location: "EU"`
- `location: "eu"`
- `location: "europe-west6"`

All queries on US servers works, but nothing in EU.
