### ISSUE TITLE
[http] allow http tools to severs with self-signed certs 

### ISSUE THREAD

**Issue by alessandro-festa** [googleapis/genai-toolbox#661]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### Question

I did not find anything in the documentation, so I'm posting here the question:
Let say I have an HTTP source that has a self-signed certifcate (i.e.: for developing purposes) and I want to use that source as tool.
Is there a way to pass any parameter to ingnore the selfsigned certificate ? Something similar to:
```
sources:
    my-http-source:
        kind: http
        baseUrl: https://api.mydomain.com
        insecureHTTP: true
```

**Comment by duwenxin99** [comment]
Hi @alessandro-festa, you can now disable SSL verification by setting the `disableSslVerification` field to `true`:

```
sources:
    my-http-source:
        kind: http
        baseUrl: https://api.mydomain.com
        disableSslVerification: true
```

Let me know if you get further questions. Thanks for your input!
