### ISSUE TITLE
Add Support for URL path parameters to HTTP Tool

### ISSUE THREAD

**Issue by ronsonx** [googleapis/genai-toolbox#680]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

Currently, when configuring an `http` tool that requires parameters in the URL path (e.g., https://api.example.com/users/{userId}), there is no dedicated section to define these path parameters.

### Suggested Solution(s)

I propose adding a new, dedicated section called `pathParams `for defining URL path parameters within an `http` tool definition.

This new section would have the same structure as `queryParams`, `bodyParams`, and `headerParams`. Parameters defined under `pathParams` would be available for substitution in the `path` field using the `{{.paramName}}` syntax.

With this new section, the example above would be configured as follows:
```yaml
# Proposed Solution
get-weather-forecast:
  kind: http
  source: nws-api
  method: GET
  path: /points/{{.lat}},{{.lon}}
  # Parameters are now clearly and correctly defined
  pathParams:
    - name: lat
      description: "The latitude of the location."
      type: number
    - name: lon
      description: "The longitude of the location."
      type: number
```
