### ISSUE TITLE
Add a way to pass parameters to the database in sources

### ISSUE THREAD

**Issue by maciej-skorupka** [googleapis/genai-toolbox#716]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

Hi.

As far as I know, currently sources don't have a way to pass parameter for a database connection. For instance, I'm using the this structure for mysql as suggested by https://googleapis.github.io/genai-toolbox/resources/sources/mysql/

```

sources:
    my-mysql-source:
        kind: mysql
        host: 127.0.0.1
        port: 3306
        database: my_db
        user: ${USER_NAME}
        password: ${PASSWORD}
		

```

When I connect to the database, I get this error and I'd like to be able to change this _require_secure_transport_ value. Nevertheless, this I'd like to be able to generally change parameters related to connectivity etc.

`2025-06-16T14:42:27.1064573+02:00 ERROR "toolbox failed to initialize: unable to initialize source \"mysource\": unable to connect successfully: Error 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON."`

I'm using toolbox 0.7.0.
