### ISSUE TITLE
Special characters not working as mssql password

### ISSUE THREAD

**Issue by maciej-skorupka** [googleapis/genai-toolbox#717]
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

0.7.0

### Environment

1. OS type and version: Windows 11
2. How are you running Toolbox: 
  - As a downloaded binary directly from github

### Client

1. Client: running a command line on windows 

```bash
toolbox.exe --tools-file "tools.yaml" --log-level DEBUG
```

### Expected Behavior

I'd like toolbox to connect to the database even when the password contains special characters

### Current Behavior

2025-06-16T17:24:21.8764283+02:00 ERROR "toolbox failed to initialize: unable to initialize source \"mysource\": unable to connect successfully: parse \"sqlserver://username:113%0SoAda2m@somedatabase.database.windows.net:1433?database=mydb\": invalid URL escape \"%0S\""

### Steps to reproduce?

1. Run "toolbox.exe --tools-file "tools.yaml" --log-level DEBUG"
2. tools.yaml content:

```yaml
sources:
    mysource:
        kind: mssql
        host: somedatabase.database.windows.net
        port: 1433
        database: mydb
        user: username
        password: '113%0SoAda2m'
        
        
```

**Comment by maciej-skorupka** [comment]
Nevermind. The error made me realize that I can just encode the password inside YAML with URI encoding, so % becomes %25. Nevertheless it might be good to have this mentioned in the docs.

**Comment by Yuan325** [comment]
@maciej-skorupka Hi, thanks for opening this. Do you meant to set the `password` field as encoded password?

**Comment by maciej-skorupka** [comment]
I mean to change % to %25 inside the yaml config. Generally URL encode it.

```yaml
sources:
    mysource:
        kind: mssql
        host: somedatabase.database.windows.net
        port: 1433
        database: mydb
        user: username
        password: '113%0SoAda2m'
```

to this:

```yaml
sources:
    mysource:
        kind: mssql
        host: somedatabase.database.windows.net
        port: 1433
        database: mydb
        user: username
        password: '113%250SoAda2m'
```
