### ISSUE TITLE
Optional Null value types for parameters

### ISSUE THREAD

**Issue by mandynic** [googleapis/genai-toolbox#736]
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### What are you trying to do that currently feels hard or impossible?

Hello,

Is it possible to have null types when specifying tool parameters? For example in tools.yaml:
```
parameters: 
    - name: name 
      type: ['string', 'null']
      description: The name of the hotel.
```
